Data structures
KirillTokachev/SimbirSoftSummerWorkshop pull request #12
Opened 2021-10-22 15:59 UTC by KirillTokachev

2021-11-08 14:53 UTC, faktor600 commented on app/src/main/java/com/example/simbirsoftsummerworkshop/App.kt
> +class App : Application() {
Тогда и от App можно отказаться

2021-11-08 15:41 UTC, KirillTokachev commented on app/src/main/java/com/example/simbirsoftsummerworkshop/App.kt
> +class App : Application() {
Сделал

2021-11-09 07:47 UTC, KirillTokachev commented on app/src/main/java/com/example/simbirsoftsummerworkshop/view/fragments/MainFragment.kt
> +    private fun showBottomNav() {
сделал

2021-11-11 12:24 UTC, faktor600 requested changes

2021-11-17 06:45 UTC, KirillTokachev commented on app/src/main/java/com/example/simbirsoftsummerworkshop/model/DataServise.kt
> +    private val events: List<Datas.Event> by lazy {
сделал

2021-11-17 08:26 UTC, KirillTokachev commented on app/src/main/java/com/example/simbirsoftsummerworkshop/model/DataServise.kt
> +    private val events: List<Datas.Event> by lazy {
val свойство не может же иметь set

2021-11-17 08:48 UTC, KirillTokachev commented on app/src/main/java/com/example/simbirsoftsummerworkshop/view/news/NewsFragment.kt
> +        if (DataServise.getNews().isEmpty()) {
сделал

2021-11-17 08:50 UTC, KirillTokachev commented on app/src/main/java/com/example/simbirsoftsummerworkshop/view/profile/CameraFragment.kt
> +        if (allPermissionsGranted()) {
сделал

2021-11-17 08:51 UTC, KirillTokachev commented on app/src/main/java/com/example/simbirsoftsummerworkshop/viewmodel/NewsViewModel.kt
> +class NewsViewModel(/*private val service: DataServise*/) : ViewModel() {
убрал

2021-11-17 08:51 UTC, KirillTokachev commented on app/src/main/res/values/dimens_fragmen.xml
> +<?xml version="1.0" encoding="utf-8"?>
исправил)

2021-11-17 08:57 UTC, KirillTokachev commented on app/src/main/java/com/example/simbirsoftsummerworkshop/utils/Util.kt
> +        return if (relevanceDate(news.dateEnd)) {
сделал

2021-11-17 09:05 UTC, KirillTokachev commented on app/src/main/java/com/example/simbirsoftsummerworkshop/viewmodel/ProfileViewModel.kt
> +    private val uriFile: MutableLiveData<Uri> by lazy {
ну я так делаю что бы было более безопасно, можно же при записи в livedata проверять валидность данных например что бы ничего лишнего не передалось, да по всем доком так в примерах делается. Не очень хорошо же когда есть напрямую доступ к MutableLiveData.
Хотелось бы так оставить)

2021-11-17 09:05 UTC, KirillTokachev commented on app/src/main/res/values/dimens_fragmen.xml
> +
исправил

2021-11-17 09:06 UTC, KirillTokachev commented on app/src/main/java/com/example/simbirsoftsummerworkshop/view/profile/CameraFragment.kt
> +                // finish()
убрал

2021-11-17 09:10 UTC, KirillTokachev commented on app/src/main/java/com/example/simbirsoftsummerworkshop/view/fragments/MainFragment.kt
> +
исправил

2021-11-17 09:20 UTC, KirillTokachev commented on app/src/main/java/com/example/simbirsoftsummerworkshop/view/fragments/MainFragment.kt
> +            VISIBLE -> {
исправил

2021-11-21 13:43 UTC, faktor600 commented on app/src/main/java/com/example/simbirsoftsummerworkshop/model/DataServise.kt
> +    private val events: List<Datas.Event> by lazy {
Сделай var и можно будет) Я просто написал как пример

2021-11-21 13:44 UTC, merged

2021-11-21 13:45 UTC, faktor600 commented on app/src/main/java/com/example/simbirsoftsummerworkshop/model/DataServise.kt
> +    private val events: List<Datas.Event> by lazy {
Не буду держать пр ради этого, смержу