Training java part2
KirillTokachev/SimbirSoftSummerWorkshop pull request #6
Opened 2021-08-01 22:32 UTC by KirillTokachev

2021-08-02 16:27 UTC, faktor600 commented on app/src/main/java/trainingJavaPart2/DirectionsTask/ReleasedDirections.java
> +                    coordinatChanges(location[0] = location[0], location[1] += 1, path[i]);
Ты считай в передаче параметров функции делаешь ее же работу) У тебя функция возвращает значения координат, приравнивай location координаты к тем, которые возвращаются функцией

2021-08-02 16:28 UTC, faktor600 commented on app/src/main/java/trainingJavaPart2/DirectionsTask/ReleasedDirections.java
> +                    coordinatChanges(location[0] = location[0], location[1] += 1, path[i]);
Просьба на каждый мой коммент как то отписываться, чтобы я видел, что ты прочитал и сделал.

2021-08-02 16:41 UTC, faktor600 requested changes

2021-08-02 16:41 UTC, faktor600 commented on app/src/main/java/trainingJavaPart2/Lambda.java
> +        return "I Love Java!";
И тут же `System.out.println`

2021-08-02 16:41 UTC, faktor600 commented on app/src/main/java/trainingJavaPart2/Lambda.java
> +    public void repeatTask(int times) {
`repeatTask` должна принимать `times` и `runnable`, который уже будет в цикле выполнять лямбда-выражение

2021-08-02 16:43 UTC, faktor600 commented
`replaceAllNumbers` 

`for (int i = 0; i < text.length(); i++){
            String key = text.substring(i, i + 1);
            if (mapInt.containsKey(key)){
                result = result + mapInt.get(key);
            } else {
                result = result + key;
            }
        }
        return result;
    }`

Здесь когда ты каждый раз, когда изменяешь строку result, то она будет каждый пересоздаваться. Чтобы такого не было, нужно использовать StringBuilder

2021-08-02 17:28 UTC, faktor600 requested changes

2021-08-02 17:28 UTC, faktor600 commented on app/src/main/java/trainingJavaPart2/Time.java
> +    private final int MIN = 60;
Я бы назвал MIN_SECOND, либо вынес бы еще 60 как SECOND

2021-08-02 17:28 UTC, faktor600 commented on app/src/main/java/trainingJavaPart2/abonentTask/Subscriber.java
> +    private long debitCard;
Просто `debit`

2021-08-02 17:28 UTC, faktor600 commented on app/src/main/java/trainingJavaPart2/abonentTask/Subscriber.java
> +    private long debitCard;
Не хватает кредита

2021-08-02 17:28 UTC, faktor600 commented on app/src/main/java/trainingJavaPart2/abonentTask/Subscriber.java
> +        this.timeCalsIntercity = timeCalsIntercity;
Зачем сетишь параметры?

2021-08-02 17:28 UTC, faktor600 commented on app/src/main/java/trainingJavaPart2/abonentTask/Subscriber.java
> +        if(Long.toString(debitCard).length() != 10);
Так же считаю, что проверки стоит вынести в set методы

2021-08-02 17:28 UTC, faktor600 commented on app/src/main/java/trainingJavaPart2/abonentTask/Subscriber.java
> +    public void setCreditCard(long creditCard) { this.creditCard = creditCard; }
Стиль

2021-08-02 17:28 UTC, faktor600 commented on app/src/main/java/trainingJavaPart2/abonentTask/Subscriber.java
> +    public void setId(long id) {
Здесь же сделал в set)

2021-08-02 17:28 UTC, faktor600 commented on app/src/main/java/trainingJavaPart2/abonentTask/Subscriptions.java
> +    public static String toCals(ArrayList<Subscriber> inputList, int time){
Не очень название функции, лучше `getSubscribersWithExceedingCallTime`

2021-08-02 17:28 UTC, faktor600 commented on app/src/main/java/trainingJavaPart2/abonentTask/Subscriptions.java
> +    public static String toCalsIntercity(ArrayList<Subscriber> inputList){
Здесь так же

2021-08-02 17:28 UTC, faktor600 commented on app/src/main/java/trainingJavaPart2/studentTask/StudentsTask.java
>          DateTimeFormatter formatterOld = DateTimeFormatter.ofPattern("dd/MM/yyyy");
Хотелось бы узнать, зачем тут `DateTimeFormatter`, которые не используются?

2021-08-02 17:28 UTC, faktor600 commented on app/src/main/java/trainingJavaPart2/internetshop/Administrator.java
> +    public void orderRegistration(Client client) {
Я бы назвал `checkIsOrderPayed`

2021-08-03 05:48 UTC, faktor600 commented
Убрать файлы java 1

2021-08-04 11:13 UTC, KirillTokachev commented on app/src/main/java/trainingJavaPart2/DirectionsTask/ReleasedDirections.java
> +                    coordinatChanges(location[0] = location[0], location[1] += 1, path[i]);
Исправил на location = coordinatChanges(path[i], location[0], location[1]);

2021-08-04 12:15 UTC, KirillTokachev commented on app/src/main/java/trainingJavaPart2/Lambda.java
> +    public void repeatTask(int times) {
Переделал полностью практически 
interface Runnable {

    void print();
}
public class Lambda {

    Runnable myClosure = () -> System.out.println("I Love Java");

    public void repeatTask(int times, Runnable task) {
        for (int i = 0; i < times; i++) {
            task = myClosure;
            task.print();
        }
    }
}

2021-08-04 12:38 UTC, KirillTokachev commented on app/src/main/java/trainingJavaPart2/MyArray.java
> +    public int numberOfDifferentElements (ArrayList<Integer> input){
Исправил

2021-08-04 13:17 UTC, KirillTokachev commented on app/src/main/java/trainingJavaPart2/MyArray.java
> +            int index = random.nextInt(i + 1);
переделал метод в более стабильный,поменял алгоритм.
public ArrayList<Integer> getRandomElement () {
        // Лёгкий способ
        /*Collections.shuffle(myArray);*/
        int tmp;

        for (int i = 0; i < myArray.size(); i++){
            int buf1 = (int) (Math.random() * myArray.size());
            int buf2 = (int) (Math.random() * myArray.size());
            tmp = myArray.get(buf1);
            myArray.set(buf1, myArray.get(buf2));
            myArray.set(buf2, tmp);
        }

2021-08-04 13:19 UTC, KirillTokachev commented on app/src/main/java/trainingJavaPart2/Time.java
> +    private final int MIN = 60;
Исправил на MIN_SECOND

2021-08-04 13:26 UTC, KirillTokachev commented on app/src/main/java/trainingJavaPart2/abonentTask/Subscriber.java
> +    private long debitCard;
исправил, добавил

2021-08-04 13:26 UTC, KirillTokachev commented on app/src/main/java/trainingJavaPart2/abonentTask/Subscriber.java
> +        this.timeCalsIntercity = timeCalsIntercity;
Ошибочка)
убрал

2021-08-04 13:28 UTC, KirillTokachev commented on app/src/main/java/trainingJavaPart2/abonentTask/Subscriber.java
> +        if(Long.toString(debitCard).length() != 10);
Сделал)

2021-08-04 13:33 UTC, KirillTokachev commented on app/src/main/java/trainingJavaPart2/abonentTask/Subscriptions.java
> +    public static String toCals(ArrayList<Subscriber> inputList, int time){
Да соглласен,переделала

2021-08-04 13:33 UTC, KirillTokachev commented on app/src/main/java/trainingJavaPart2/abonentTask/Subscriptions.java
> +    public static String toCalsIntercity(ArrayList<Subscriber> inputList){
Аналогично

2021-08-04 13:38 UTC, KirillTokachev commented on app/src/main/java/trainingJavaPart2/studentTask/StudentsTask.java
>          DateTimeFormatter formatterOld = DateTimeFormatter.ofPattern("dd/MM/yyyy");
Забыл убрать, извиняюсь за невнимательность

2021-08-04 13:39 UTC, KirillTokachev commented on app/src/main/java/trainingJavaPart2/internetshop/Administrator.java
> +    public void orderRegistration(Client client) {
Переделал

2021-08-04 13:40 UTC, KirillTokachev commented
Удалил файлы java 1

2021-08-04 18:49 UTC, faktor600 commented on app/src/main/java/trainingJavaPart2/Lambda.java
> +    public void repeatTask(int times) {
Вот теперь ок

2021-08-04 18:57 UTC, merged