Kotlin part 1
KirillTokachev/SimbirSoftSummerWorkshop pull request #7
Opened 2021-08-02 07:41 UTC by KirillTokachev

2021-08-02 17:31 UTC, faktor600 commented on app/src/main/java/trainingKotlinPart1/Publication.kt
> +    fun getType(s: String): String
Ну если переменная в функции не используется, то ее можно убрать

2021-08-02 17:41 UTC, faktor600 requested changes

2021-08-02 17:41 UTC, faktor600 commented on app/src/main/java/trainingKotlinPart1/Test.kt
> +    val book3 = n?.let { Book(it,2341) }
Под задачей "Создать две переменных класса Book, в которых могут находиться null значения. Присвоить одной null, а второй любое notnull значение и вызвать метод buy с каждой из переменных." подразумевалось 

`val bookNull: Book? = null
val bookNotNull: Book? = Book(...)` 

И уже над ними производить операцию `buy`

2021-08-02 17:41 UTC, faktor600 commented on app/src/main/java/trainingKotlinPart1/Book.kt
> +            in 1001..15000 -> result = "Novel"
Количество слов может быть выше 15000, сделай через `wordCount > 1000` и 1000 вынеси в константу

2021-08-02 17:42 UTC, faktor600 commented
Ненужные файлы от java, убери. Они заедут 2 реквестами в develop

2021-08-04 13:47 UTC, KirillTokachev commented on app/src/main/java/trainingKotlinPart1/Publication.kt
> +    fun getType(s: String): String
Убрал

2021-08-04 13:54 UTC, KirillTokachev commented on app/src/main/java/trainingKotlinPart1/Publication.kt
> +    fun getType(s: String): String
так это метод переопределяется для того что бы принимать название и возвращать результат исходя из параметров переданых в функцию, просток как сделать по другому этот метод я не знаю. Сделал как умею и он работает)

2021-08-04 14:01 UTC, KirillTokachev commented on app/src/main/java/trainingKotlinPart1/Book.kt
> +            in 1001..15000 -> result = "Novel"
сделал проше result = if (wordCount <= 1000) "Flash Fiction”, 7,500 –“Short Story" else "Novel"

2021-08-04 14:10 UTC, KirillTokachev commented on app/src/main/java/trainingKotlinPart1/Test.kt
> +    val book3 = n?.let { Book(it,2341) }
ну тут очевидно что сам Kotlin не даст запустить метод без проверки на bull, ну а если всё же использовать !! то естественно выйдет ошибка NullPointerException

2021-08-04 14:49 UTC, faktor600 commented on app/src/main/java/trainingKotlinPart1/Test.kt
> +    val book3 = n?.let { Book(it,2341) }
Я с тобой согласен, но это просто обучающее задание, этот код нигде не будет использоваться. Оно просто показывает, понимаешь ли то, как правильно определять nullable переменные в котлине

2021-08-04 16:33 UTC, faktor600 requested changes

2021-08-04 18:36 UTC, faktor600 commented
Окей, штука с функцией сейчас не критична. Но в дальнейшем не нужно оставлять аргументы, которые не используются

2021-08-04 18:36 UTC, merged