Kotlin part 2
KirillTokachev/SimbirSoftSummerWorkshop pull request #8
Opened 2021-08-02 14:59 UTC by KirillTokachev

2021-08-02 17:42 UTC, faktor600 commented
По java тоже самое

2021-08-02 17:44 UTC, faktor600 commented
И по 1 части котлина тоже убери, здесь должны быть файлы только по 2 части котлина

2021-08-02 18:07 UTC, faktor600 requested changes

2021-08-02 18:07 UTC, faktor600 commented on app/src/main/java/trainingKotlinPart2/Test.kt
> +    if (User().age >= 18){
Использовать реализованную функцию valdiate()

2021-08-02 18:07 UTC, faktor600 commented on app/src/main/java/trainingKotlinPart2/Action.kt
> +    class Registration() : Action()
Если нет параметров, то можно делать через `object`

2021-08-02 18:07 UTC, faktor600 commented on app/src/main/java/trainingKotlinPart2/Test.kt
> +        Action.Login(User()) -> auth { updateCache() }
Тоже выводить лог о логине

2021-08-02 18:07 UTC, faktor600 commented on app/src/main/java/trainingKotlinPart2/Test.kt
> +inline fun auth (updateCache: () -> Unit) {
Переименовать `updateCache`. К примеру просто `func`

2021-08-02 18:07 UTC, faktor600 commented on app/src/main/java/trainingKotlinPart2/Test.kt
> +        updateCache()
Вызывать параметр функции

2021-08-02 18:08 UTC, faktor600 commented on app/src/main/java/trainingKotlinPart2/User.kt
> +data class User(val id: Int, val name: String, val age: Int, val type: Type){
Читать удобнее

2021-08-04 14:14 UTC, KirillTokachev commented on app/src/main/java/trainingKotlinPart2/User.kt
> +data class User(val id: Int, val name: String, val age: Int, val type: Type){
Сделал)

2021-08-04 14:21 UTC, KirillTokachev commented on app/src/main/java/trainingKotlinPart2/Test.kt
> +class Test {
Сделал
fun sleep (user: User){
    Log.i("sleep", user.startTime)
    Thread.sleep(1000)
    Log.i("sleep", user.startTime)
}

2021-08-04 14:33 UTC, KirillTokachev commented on app/src/main/java/trainingKotlinPart2/Test.kt
> +    user.forEach { if (it.type == Type.FULL) Log.i("test", "Полный доступ имеют: ${it.name}") }
Сделал

2021-08-04 14:40 UTC, KirillTokachev commented on app/src/main/java/trainingKotlinPart2/Test.kt
> +fun fullAccess (user: List<User>){
Сделал

2021-08-04 14:42 UTC, KirillTokachev commented on app/src/main/java/trainingKotlinPart2/Test.kt
> +inline fun auth (updateCache: () -> Unit) {
Сделал

2021-08-04 18:58 UTC, faktor600 requested changes

2021-08-04 18:58 UTC, faktor600 commented on app/src/main/java/trainingKotlinPart2/Test.kt
> +    User().validate(User().age)
Хочу увидеть это https://kotlinlang.ru/docs/reference/extensions.html

2021-08-04 18:58 UTC, faktor600 commented on app/src/main/java/trainingKotlinPart2/User.kt
> +data class User(val id:
Чет уехали типы для свойств

2021-08-04 18:58 UTC, faktor600 commented on app/src/main/java/trainingKotlinPart2/Test.kt
> +    for (User in users){
С помощью `map` можно легко преобразовывать один список в другой и это умещается в одну строчку кода, поэтому и прошу сделать через этот оператор

2021-08-04 18:58 UTC, faktor600 commented on app/src/main/java/trainingKotlinPart2/User.kt
> +    fun validate (age: Int){
Пока не вижу

2021-08-04 18:58 UTC, faktor600 commented on app/src/main/java/trainingKotlinPart2/Test.kt
> +    User().validate(User().age)
Вся логика метода пропала  (Внутри функции auth вызвать метод коллбека authSuccess и переданный updateCache, если проверка возраста пользователя произошла без ошибки. В случае получения ошибки вызвать authFailed.)

2021-08-04 18:58 UTC, faktor600 commented on app/src/main/java/trainingKotlinPart2/Test.kt
> +        Action.Registration() -> Log.i("test", "Registered")
Не надо создавать экземпляры классов, здесь нужна обычная проверка

2021-08-04 18:58 UTC, faktor600 commented on app/src/main/java/trainingKotlinPart2/Test.kt
> +        Action.Registration() -> Log.i("test", "Registered")
Да и не сработает это, так как будут разные объекты

2021-08-05 05:49 UTC, KirillTokachev commented on app/src/main/java/trainingKotlinPart2/Test.kt
> +    for (User in users){
Сделал

2021-08-05 06:04 UTC, KirillTokachev commented on app/src/main/java/trainingKotlinPart2/User.kt
> +    fun validate (age: Int){
Сделал

2021-08-05 06:05 UTC, KirillTokachev commented on app/src/main/java/trainingKotlinPart2/Test.kt
> +    if (User().age >= 18){
Сделал

2021-08-05 06:05 UTC, KirillTokachev commented on app/src/main/java/trainingKotlinPart2/Action.kt
> +    class Registration() : Action()
Сделал

2021-08-06 07:25 UTC, KirillTokachev commented on app/src/main/java/trainingKotlinPart2/Action.kt
> +    class Registration() : Action()
точно, исправил)

2021-08-06 07:30 UTC, KirillTokachev commented on app/src/main/java/trainingKotlinPart2/User.kt
> +data class User(val id:
поправил

2021-08-06 13:44 UTC, KirillTokachev reviewed
в функции doAction тоже добавил user в параметры, так как Login принимает его в качеcтсве параметра и без него не будет выполняться метода auth

2021-08-06 13:56 UTC, faktor600 commented on app/src/main/java/trainingKotlinPart2/Test.kt
> +        func()
func().invoke()

2021-08-06 13:56 UTC, faktor600 commented on app/src/main/java/trainingKotlinPart2/Test.kt
> +
Стиль

2021-08-06 14:04 UTC, KirillTokachev commented on app/src/main/java/trainingKotlinPart2/Test.kt
> +        func()
так? func().run { updateCache() }

2021-08-06 14:38 UTC, KirillTokachev commented on app/src/main/java/trainingKotlinPart2/Test.kt
> +
исправил

2021-08-06 14:39 UTC, KirillTokachev commented on app/src/main/java/trainingKotlinPart2/Test.kt
> +        func()
если имеется ввиду перегрузка фунцкции разве она не перегружается при вызове auth(Io, ::updateCache) ?

2021-08-17 07:09 UTC, KirillTokachev commented on app/src/main/java/trainingKotlinPart2/Test.kt
> +        updateCache()
исправил 
inline fun auth(user: User, func: () -> Unit){
    try {
        user.validate()
        obj.authSuccess()
        func()
    } catch (e:Exception) {
        obj.authFailed()
    }
}

2021-08-17 07:09 UTC, KirillTokachev commented on app/src/main/java/trainingKotlinPart2/Test.kt
> +    User().validate(User().age)
inline fun auth(user: User, func: () -> Unit){
    try {
        user.validate()
        obj.authSuccess()
        func()
    } catch (e:Exception) {
        obj.authFailed()
    }
}

2021-08-17 07:10 UTC, KirillTokachev commented on app/src/main/java/trainingKotlinPart2/Test.kt
> +        Action.Registration() -> Log.i("test", "Registered")
fun doAction (action: Action, user: User){
    when (action){
        is Action.Login -> auth(user, ::updateCache)
        is Action.Logout -> Log.d("test", "Logout")
        is Action.Registration -> Log.d("test", "Registered")
    }
}

2021-08-17 07:10 UTC, KirillTokachev commented on app/src/main/java/trainingKotlinPart2/Test.kt
> +        Action.Registration() -> Log.i("test", "Registered")
сделал так

2021-08-17 11:39 UTC, faktor600 requested changes

2021-08-17 12:02 UTC, KirillTokachev commented on app/src/main/java/trainingKotlinPart2/Test.kt
> +        func()
сделал
inline fun auth(user: User, func: () -> Unit){
    try {
        user.validate()
        obj.authSuccess()
        func.invoke()
    } catch (e:Exception) {
        obj.authFailed()
    }
}

2021-08-17 20:11 UTC, merged